Repository vaticle/factory-tracing, pull requests merged in 2020-07, with the labels that each got.

#23 Integrate building with BuildBuddy
  .bazelrc
  .bazelversion
  dependencies/graknlabs/dependencies.bzl
Labels: priority: high, type: build

#22 Update proto file to handle Long analysis ids
  client/GrablTracingStandard.java
  client/TraceStream.java
  client/test/GrablTracingClientTest.java
  example/BUILD
  example/ExampleTracingServer.java
  protocol/tracing.proto
Labels: priority: high, type: feature

#24 Permit tracing no-op when context not supplied
  client/GrablTracingThreadStatic.java
Labels: type: feature

#25 Ping keep alive so that tracing stream doesn't get dropped during idle
  client/GrablTracing.java
Labels: type: bug
