Repository vaticle/factory-tracing, pull requests merged in 2020-12, with the labels that each got.

#43 Build Java code to be compatible with older Java
  .bazelrc
Labels: priority: high, type: build

#42 Updated grabl tracing to send analysis name
  client/GrablTracing.java
  client/GrablTracingNoOp.java
  client/GrablTracingSlf4j.java
  client/GrablTracingStandard.java
  client/GrablTracingThreadStatic.java
  client/test/GrablTracingClientTest.java
  example/ExampleTracingClient.java
  protocol/tracing.proto
Labels: priority: high, type: bug

#44 Adapt to new Grabl syntax
  .grabl/automation.yml
Labels: priority: high, type: build, type: refactor
